---
name: release-notification

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  notify-on-release:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Notification on new release
        uses: cbrgm/telegram-github-action@14bbb5d52c0dddd791c3bc9b2f1c4820da59395b # v1.3.14
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          message: |
            ðŸš€ New Release Published!
            Release Name: ${{ github.event.release.name }}
            Tag: ${{ github.event.release.tag_name }}
            Actor: ${{ github.actor }}
            Repository: ${{ github.repository }}
            Check it out: ${{ github.event.release.html_url }}

      - name: Send Mastodon Status on new release
        id: mastodon
        uses: cbrgm/mastodon-github-action@fc8b40e2ec9e8208654b0bd8695e03ecc3364d7d # v2.1.26
        if: ${{ !github.event.repository.private }}
        with:
          access-token: ${{ secrets.MASTODON_ACCESS_TOKEN }}
          url: ${{ secrets.MASTODON_URL }}
          language: "en"
          message: |
            ðŸš€  ${{ github.repository }} ${{ github.event.release.name }} published!
            Check it out: ${{ github.event.release.html_url }}
...
